server:
  port: 7002
spring:
  application:
    name: GATEWAYSERVER
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示浏览器中的状态栏显示ip
zuul:
  routes:
    myuserserver:
      path: /userserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: USERSERVICE
#    myorderserver:
#      path: /orderserver/**        #http://localhost:7003/userserver/user/show?uid=2
#      serviceId: ORDERSERVER
#    mygoodsserver:
#      path: /goodsserver/**        #http://localhost:7003/userserver/user/show?uid=2
#      serviceId: GOODSSERVER

