server:
  port: 7002
spring:
  application:
    name: GATEWAYSERVER
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示浏览器中的状态栏显示ip
zuul:
  routes:
    myuserserver:

      path: /userserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: USERSERVICE
    authserver:
      path: /authserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: auth2.server
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

      path: /classservice/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: CLASSSERVICE
#    myorderserver:
#      path: /orderserver/**        #http://localhost:7003/userserver/user/show?uid=2
#      serviceId: ORDERSERVER

#    mygoodsserver:
#      path: /goodsserver/**        #http://localhost:7003/userserver/user/show?uid=2
#      serviceId: GOODSSERVER
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000
