server:
  port: 7002
spring:
  application:
    name: GATEWAYSERVER
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示浏览器中的状态栏显示ip
zuul:
  routes:
    issueserver:
      path: /issueserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: ISSUESERVER
<<<<<<< HEAD
    notificationserver:
      path: /notificationserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: NOTIFICATIONSERVER
=======
>>>>>>> master
    surveyserver:
      path: /surveyserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: SURVEYSERVER
    scoreserver:
      path: /scoreserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: SCORESERVER
    myuserserver:
      path: /userserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: USERSERVICE
    authserver:
      path: /authserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: auth2.server

#    myorderserver:
#      path: /orderserver/**        #http://localhost:7003/userserver/user/show?uid=2
#      serviceId: ORDERSERVER

#    mygoodsserver:
#      path: /goodsserver/**        #http://localhost:7003/userserver/user/show?uid=2
#      serviceId: GOODSSERVER
qiniu:
  accessKey: ZFYhmom1h56k40C8hBzlx_fVcvsJRcvytGxrDo4L
  secretKey: M6p0Uta1CEjw1j-Sx_bX-U8Ikb4lUN8QFrZxGXDJ
  bucket: mydemo5418
  path: http://q89nsulx9.bkt.clouddn.com/

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

