server:
  port: 7002
  connectionTimeout: 180000
spring:
  application:
    name: GATEWAYSERVER
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示浏览器中的状态栏显示ip
zuul:
  routes:
    issueserver:
      path: /issueserver/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: ISSUESERVER
#    myorderserver:
#      path: /orderserver/**        #http://localhost:7003/userserver/user/show?uid=2
#      serviceId: ORDERSERVER
#    mygoodsserver:
#      path: /goodsserver/**        #http://localhost:7003/userserver/user/show?uid=2
#      serviceId: GOODSSERVER
qiniu:
  accessKey: ZFYhmom1h56k40C8hBzlx_fVcvsJRcvytGxrDo4L
  secretKey: M6p0Uta1CEjw1j-Sx_bX-U8Ikb4lUN8QFrZxGXDJ
  bucket: mydemo5418
  path: http://q6nz2qzez.bkt.clouddn.com/
